org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

SUPABASE_URL=https://boyepuzbquqtpwmzwdmc.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveWVwdXpicXVxdHB3bXp3ZG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5ODY4MjgsImV4cCI6MjEwMzU2MjgyOH0.u9BlWdoHjInYE5-PzwYEUg-LhTsMniqJV9t-gmPXmzI
