org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=1g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Kotlin compiler & KSP daemon configuration
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1g --add-opens=java.base/java.lang=ALL-UNNAMED
kotlin.compiler.execution.strategy=in-process

SUPABASE_URL=https://boyepuzbquqtpwmzwdmc.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveWVwdXpicXVxdHB3bXp3ZG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc5ODY4MjgsImV4cCI6MjEwMzU2MjgyOH0.u9BlWdoHjInYE5-PzwYEUg-LhTsMniqJV9t-gmPXmzI

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
